exp:
  seed : 10
  lr : 0.0001
  epochs : 5
  dataset_path : /data/processed/corruptmnist/train.pt
  trained_model_path : /models/mnist/trained_model.pt
  training_loss_img_path : /reports/figures/training_loss.png